services:
  frontend:
    build:
      context: ./fullstack-app-react
      dockerfile: Dockerfile.dev
      args:
        REACT_APP_BACKEND_URL: http://fullstack-app-backend:8082
    container_name: fullstack-app-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./fullstack-app-react:/app
      - /app/node_modules
    networks:
      - my_network

networks:
  my_network:
    external: true
